language: node_js
node_js:
- 6
os:
- linux
- osx
install:
- npm install --global https://github.com/reasonml/esy/archive/beta-v0.0.4.tar.gz
- esy install
script:
- esy build
- esy ./_build/bin/hello.byte
- esy ./_build/bin/hello.native

