language: node_js
node_js:
- 6
os:
- linux
- osx
before_install:
- npm install --global git://github.com/jordwalke/esy.git#beta-v0.0.2
script:
- esy install
- esy build
- esy ./_build/bin/hello.byte
- esy ./_build/bin/hello.native

